root: ./

redirects:
  setup/mainsail-os: setup/getting-started.md
  theming/themes: overview/features/themes/themes.md
  remotemode: overview/quicktips/config-json.md
  configuration: setup/configuration.md
