name: Update Themes

on:
  push:
    branches:
      - main
    files:
      - './_data/themes.csv'
      - './_scripts/generate-themes.js'
      - './_scripts/theme-entry.md'
      - './_scripts/themes.md'
  workflow_dispatch:

jobs:
  update-themes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: v18.x

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: npm install
        run: npm ci

      - name: Generate themes.md
        run: node ./_scripts/generate-themes.js

      - name: git add & commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'overview/features/themes/themes.md'
          default_author: github_actions
          message: 'docs: update themes.md'
          push: true